Arpit/asset_management/config/routes.rb
Rails.application.routes.draw do

  resources :invoices do
    collection do
      get 'get_purchase_order'
    end
  end
  get 'download'=> "welcome#download_file",as: :download

  resources :purchase_orders

  resources :transfers do
    member do
      get 'resources'
    end
  end

  resources :quotations do
    member do
      get 'request_vendors'
      get 'get_requests'
    end
  end

  resources :device_requests
  resources :device_assignments
  resources :device_categories

  resources :devices do
    collection do
      get 'assignment'
      post 'check_serial_uniqueness'
      post 'assignment'
      put 'update_assignment'
    end
    member do
      delete 'destroy_assignment'
    end
  end

  namespace :admin do
    resources :users
  end
  resources :clients
  resources :branches do
    member do
      get 'get_employees'
	  get 'associate_data'
    end
  end
  resources :vendors
  resources :software_products
  resources :employees
  get 'welcome/index'  # The priority is based upon order of creation: first created -> highest priority.

  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Arpit/asset_management/app/models/quotation.rb
class Quotation < ActiveRecord::Base

  # Relationships
  belongs_to :device_request
  has_many :device_transactions
  has_many :uploads, as: :attachable
  has_one :purchase_order
  accepts_nested_attributes_for :purchase_order, :allow_destroy => true
  accepts_nested_attributes_for :device_transactions, :allow_destroy => true
  accepts_nested_attributes_for :uploads, :allow_destroy => true
  attr_accessor :vendor_id

  # Validations
  validates :device_request_id, :on_date, presence: true
  validate :valid_dates

  # Callbacks
  before_create :generate_identifier
  after_destroy :nullify_transactions


  def update_transaction(quotation_datas)
    quotation_datas.each do |transaction_id, quotation_value|
      transaction = DeviceTransaction.find(transaction_id)
      transaction.update_attributes(quotation_id: id, quotation_title: quotation_value['quotation_title'], quotation_description: quotation_value['quotation_description'], quotation_price: quotation_value['quotation_price'], quotation_quantity: quotation_value['quotation_quantity'])
    end
  end

  def edit?
    self.purchase_order.blank?
  end


  private

  def generate_identifier
    if Quotation.exists?
      identifier = Quotation.last.identifier
      identifier = (identifier.gsub("QOT", "").to_i + 1).to_s.prepend("QOT")
    else
      identifier = "QOT1"
    end
    self.identifier = identifier
  end

  # Custom Validation method for restrict date of invoice not to be less then current date and purchase order date
  def valid_dates
    device_request = DeviceRequest.find(device_request_id)
    current_date = Date.today
    if self.on_date.present?
      self.errors.add :on_date, "Quotation date can't be future" if self.on_date > current_date
      self.errors.add :on_date, "Quotation date should be onwards #{device_request.on_date}" if self.on_date < device_request.on_date
    end
  end

  # Nullify quotations data from transactions table
  def nullify_transactions
    device_transactions.update_all(quotation_id: nil, quotation_title: nil, quotation_description: nil, quotation_price: nil, quotation_quantity: nil, quotation_notes: nil)
  end

end

Arpit/asset_management/app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :device_request_list , only: [:new, :create]
  before_action :check_permission, only: [:edit, :destroy, :update]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    if params[:device_request_id]
      @device_request = DeviceRequest.find(params[:device_request_id])
      if @device_request
        vendor_ids = DeviceTransaction.where(device_request_id: params[:device_request_id], quotation_id: nil).map(&:vendor_id).uniq
        @vendors = Vendor.where(:id => vendor_ids)
        @device_transactions = @device_request.device_transactions.where(vendor_id: params[:vendor_id])
        @device_transactions.each do |po|
          po.quotation_title = po.request_title
          po.quotation_quantity = po.request_quantity
          po.quotation_description = po.request_description
        end
        @quotation = @device_request.quotations.build
        @quotation.device_request_id = params[:device_request_id]
        @quotation.vendor_id = params[:vendor_id]
      end
    else
      @device_request = DeviceRequest.new
      @quotation = @device_request.quotations.build
    end
    @uploads = @quotation.uploads.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /quotations/1/edit
  def edit
    @device_request = Quotation.find(params[:id]).device_request
    @uploads = @quotation.uploads.blank? ? @quotation.uploads.build : @quotation.uploads
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @device_request = DeviceRequest.find(params[:device_request_id])
    respond_to do |format|
      if @device_request.update(device_request_params)
        transactions = @device_request.device_transactions.where(vendor_id:  params[:vendor_id])
        transactions.update_all(quotation_id: @device_request.quotations.last.id)
        format.html { redirect_to @device_request.quotations.last, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @device_request.quotations.last }
      else
        @quotation = @device_request.quotations.last
        vendor_ids = DeviceTransaction.where(device_request_id: params[:device_request_id], quotation_id: nil).map(&:vendor_id).uniq
        @vendors = Vendor.where(:id => vendor_ids)
        @quotation.vendor_id = params[:vendor_id]
        @device_transactions = @device_request.device_transactions.select{|transaction| transaction.vendor_id.to_s ==  params[:vendor_id]}
        @uploads = @quotation.uploads.build
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @device_request.update(device_request_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation}
      else
        @device_transactions = @device_request.device_transactions.select {|transaction| transaction[:quotation_id] == @quotation.id }
        @uploads = @quotation.uploads.blank? ? @quotation.uploads.build : @quotation.uploads
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def request_vendors
    vendor_ids = DeviceTransaction.where(:device_request_id => params[:id], quotation_id: nil).map(&:vendor_id).uniq
    @vendors = Vendor.where(:id => vendor_ids)
    respond_to do |format|
      format.json { render :json => { :vendors => @vendors } }
    end
  end

  def get_requests
	@device_request = DeviceRequest.find(params[:device_request_id])
    @transactions = DeviceTransaction.where(vendor_id: params[:vendor_id], device_request_id: params[:device_request_id])
    @transactions.each do |transaction|
      transaction.quotation_title = transaction.request_title
      transaction.quotation_quantity = transaction.request_quantity
      transaction.quotation_description = transaction.request_description
    end
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.includes(:device_transactions, :device_request).find(params[:id])
      @device_transactions = @quotation.device_transactions
      @device_request = @quotation.device_request
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_request_params
      params.require(:device_request).permit(:identifier, :device_request_id, :on_date,quotations_attributes:[:device_request_id,:on_date,:id,uploads_attributes: [:id,:name,:attachment, :attachment_file_name, :attachment_content_type, :attachment_file_size]],device_transactions_attributes:[:quotation_title,:quotation_quantity,:quotation_price,:quotation_description,:id, :quotation_notes])
    end

    def device_request_list
      device_request_ids = DeviceTransaction.where(quotation_id: nil).map(&:device_request_id).uniq
      @device_requests = DeviceRequest.where(id: device_request_ids)
    end

    def check_permission
      redirect_to quotations_path, alert: "You can't edit this Quotation." unless @quotation.edit?
    end
end

Arpit/asset_management/app/helpers/quotations_helper.rb
module QuotationsHelper
end

Arpit/asset_management/app/views/quotations/_form.html.haml
- if @quotation.new?
  - url = quotations_path(device_request_id: @device_request.id,vendor_id: @quotation.vendor_id)
  - method = "post"
-else
  - url = quotation_path(@quotation, device_request_id: @device_request.id)
  - method = "put"

#quotations
  = bootstrap_form_for @device_request ,url: url ,method: method, layout: :horizontal, control_col: "col-sm-7",label_col: "col-sm-4", html: { class: 'validate-form' } do |f|
    = f.fields_for :quotations, @quotation, :wrapper => false do |quotation_field|
      .row
        - if @quotation.new?
          .col-md-5
            = quotation_field.select :device_request_id, @device_requests.map{ |request| [request.identifier, request.id] }, { include_blank: 'Please Select', label: "Device Request<span class='required'/>".html_safe }, data: { 'rule-required' => true }
          .col-md-5
            = quotation_field.collection_select :vendor_id, @vendors||[], :id, :name, { include_blank: 'Please Select', label: "Vendor<span class='required'/>".html_safe }, data: { 'rule-required' => true }
        - else
          .col-md-5
            .form-group
              %label.control-label.col-sm-4{:for => ""}
                Request
                %span.required
              .col-sm-7
                = @quotation.device_request.identifier
          .col-md-5
            .form-group
              %label.control-label.col-sm-4{:for => ""}
                Vendor
                %span.required
              .col-sm-7
                = @quotation.device_transactions.first.vendor.name
      #date-upload-div{class: "#{@quotation.new? ? 'hide row' : 'row' }"}
        .col-md-5
          = quotation_field.text_field :on_date, placeholder: 'dd/mm/yyyy', data: { 'date-format' =>"DD/MM/YYYY", 'behaviour' => 'no-future-datetimepicker', 'rule-dateFormat' => true, 'rule-required' => true, 'start-date' => @device_request.on_date.to_s }, label: "Date <span class='required'/>".html_safe, value: f.object.try(:on_date).try(:strftime,"%d/%m/%Y")
        .col-md-5
          = quotation_field.fields_for :uploads,@uploads, :wrapper => false do |attachment_form|
            = attachment_form.file_field :attachment ,accept: ".pdf"          
          .text-right
            = link_to "#{@quotation.uploads.try(:first).try(:attachment_file_name)}", download_path(id: @quotation.uploads.try(:first).try(:id))



    #device_transaction_div{style: "#{@quotation.new? ? 'display:none' : '' }"}
      = render "/shared/device_transactions", device_transactions: @device_transactions, type: "quotation_",f: f

    .row
      #loading_div.col-md-2.col-md-offset-5.hide
        %content
          %section
            .loadingspin

    .row
      = f.button(type: 'submit', class: "btn btn-success") do
        %i{ class: "glyphicon glyphicon-ok" }
        Save

      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, quotations_path, class: "btn btn-primary"

Arpit/asset_management/app/views/quotations/_quotation_form.html.haml
- @transactions.each do |transaction|
  .row
    %fieldset
      %legend
      .col-md-5
        .form-group
          %label.control-label.col-sm-4{:for => ""}
            Title
            %span.required
          .col-sm-7
            = text_field_tag "transactions[#{transaction.id}][quotation_title]" , transaction.quotation_title, data: {'rule-required' => true, 'rule-maxlength' => 35, 'msg-maxlength' => "Maximum 35 characters", title: "Maximum 35 characters", 'rule-validName' => true, 'rule-uniqeName' => 'title' }, class: "form-control", maxlength: 35
        .form-group
          %label.control-label.col-sm-4{:for => ""}
            Qantity
            %span.required
          .col-sm-7
            = text_field_tag "transactions[#{transaction.id}][quotation_quantity]" , transaction.quotation_quantity, data: {'rule-required' => true, 'rule-number' => true,'rule-RealNumber'=> true, 'rule-maxlength' => 3, 'msg-maxlength' => "Maximum 3 digits", title: "Maximum 3 digits" }, class: "form-control input_tooltip", maxlength: 3
        .form-group
          %label.control-label.col-sm-4{:for => ""}
            Price
            %span.required
          .col-sm-7
            = text_field_tag "transactions[#{transaction.id}][quotation_price]" , transaction.quotation_price, data: {'rule-required' => true, 'rule-number' => true, 'rule-number' => true, 'rule-maxlength' => 14, 'msg-maxlength' => "Maximum 14 digits", title: "Maximum 14 digits" }, class: "form-control input_tooltip", maxlength: 14
      .col-md-5
        .form-group
          %label.control-label.col-sm-4{:for => ""}
            Description
            %span.required
          .col-sm-7
            = text_area_tag "transactions[#{transaction.id}][quotation_description]" , transaction.quotation_description, data: { 'rule-required' => true, 'rule-maxlength' => 255, 'msg-maxlength' => "Maximum 255 characters", title: "Maximum 255 characters" }, class: "form-control input_tooltip", style: "height:140px", maxlength: 255

  .row
    %fieldset
      %legend

Arpit/asset_management/app/views/quotations/edit.html.haml
%h3 Editing Quotation

= render 'form'

Arpit/asset_management/app/views/quotations/index.html.haml
%h3 Quotations

%table#data_table.table.table-striped.table-bordered
  %thead
    %tr
      %th Identifier
      %th Device Request
      %th Title
      %th Device Category
      %th Vendor
      %th Date
      = actions_th

  %tbody
    - @quotations.each do |quotation|
      %tr
        %td= link_to quotation.identifier, quotation_path(quotation.id)
        %td= link_to quotation.device_request.identifier, device_request_path(quotation.device_request.id)
        %td= quotation.device_transactions.map(&:quotation_title).uniq.join(', ')
        %td= quotation.device_transactions.map(&:device_category).compact.map(&:name).uniq.join(', ')
        %td= quotation.device_transactions.first.try(:vendor).try(:name)
        %td= quotation.on_date.try(:strftime,"%b %d, %Y")
        %td.text-center
          = link_to '', quotation, class: "glyphicon glyphicon-eye-open show-link", title: "Show"
          - if quotation.edit?
            = link_to '', edit_quotation_path(quotation), class: "glyphicon glyphicon-pencil edit-link", title: "Edit"
            = link_to '', quotation, :method => :delete, class: "glyphicon glyphicon-remove-circle delete-link", title: "Delete", :data => { :confirm => "Are you sure you want to delete: #{quotation.identifier}?" }

%br
= link_to '<span class="glyphicon glyphicon-plus-sign"></span> New'.html_safe, new_quotation_path, class: 'btn btn-primary'

Arpit/asset_management/app/views/quotations/new.html.haml
%h3 New Quotation

= render 'form'

Arpit/asset_management/app/views/quotations/show.html.haml
%h3 Quotation Details

%table.width-100
  %tr
    %th
      Identifier:
    %td
      = @quotation.identifier
  %tr
    %th
      Date:
    %td
      = @quotation.on_date.try(:to_s, "%b %d, %Y")
  %tr
    %th
      Device Request:
    %td
      = @quotation.device_request.try(&:identifier)
  %tr
    %th
      Vendor:
    %td
      = @quotation.device_transactions.first.vendor.try(:name)
  %tr
    %th 
      Attchment:
    %td
      = link_to "#{@quotation.uploads.try(:first).try(:attachment_file_name)}", download_path(id: @quotation.uploads.try(:first).try(:id))
%br
%table#search_data_table.table.table-striped.table-bordered
  %thead
    %th Device Category
    %th Title
    %th Description
    %th Quantity
    %th 
      Price
      %small (per unit)
    %th Total
  %tbody
    - total = 0
    - @quotation.device_transactions.each do |t|
      %tr
        %td= t.device_category.try(:name)
        %td= t.quotation_title
        %td= t.quotation_description
        %td= t.quotation_quantity
        %td= t.quotation_price
        %td.text-right
          %b
            = t.quotation_subtotal
            - total += t.quotation_subtotal
  %tr
    %td
      %b Total
    %td.text-right{colspan: 5}
      %b
        = total
%br
- if @quotation.edit?
  = link_to '<span class="glyphicon glyphicon-pencil "></span> Edit'.html_safe, edit_quotation_path(@quotation), class: "btn btn-success"
= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, quotations_path, class: "btn btn-primary"