Arpit/asset_management/config/routes.rb
Rails.application.routes.draw do

  resources :invoices do
    collection do
      get 'get_purchase_order'
    end
  end
  get 'download'=> "welcome#download_file",as: :download

  resources :purchase_orders

  resources :transfers do
    member do
      get 'resources'
    end
  end

  resources :quotations do
    member do
      get 'request_vendors'
      get 'get_requests'
    end
  end

  resources :device_requests
  resources :device_assignments
  resources :device_categories

  resources :devices do
    collection do
      get 'assignment'
      post 'check_serial_uniqueness'
      post 'assignment'
      put 'update_assignment'
    end
    member do
      delete 'destroy_assignment'
    end
  end

  namespace :admin do
    resources :users
  end
  resources :clients
  resources :branches do
    member do
      get 'get_employees'
	  get 'associate_data'
    end
  end
  resources :vendors
  resources :software_products
  resources :employees
  get 'welcome/index'  # The priority is based upon order of creation: first created -> highest priority.

  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Arpit/asset_management/app/models/device.rb
class Device < ActiveRecord::Base
 
  # Association
  belongs_to :invoice
  belongs_to :vendor
  belongs_to :branch
  belongs_to :device_category
  belongs_to :employee
  belongs_to :parent, class_name: "Device"
  belongs_to :client
  has_many :device_assignments
  has_many :transfers, as: :transferable, dependent: :destroy
  has_many :employees, through: :device_assignments
  has_many :child_devices, class_name: 'Device', foreign_key: :parent_id

  has_many :more_devices, :dependent => :destroy
  accepts_nested_attributes_for :more_devices, :allow_destroy => true


  # Validation
  validates :device_identifier, :serial_number, :model_number, :device_category_id,  presence: true
  validates :serial_number, uniqueness: true
  validate :check_purchase_date, :check_valid_status
  validates :device_identifier, format: { with: VALID_NAME }

  #Call Back
  before_save :update_child_devices
  before_update :check_lifetime_warranty
  after_update :release_resources

  # Constant for devices status #
  def self.status
    { instock: "In Stock", scrap: "Scrap", faulty: "Faulty", returned: "Returned", assigned: "Assigned" }
  end

  def name
    "#{device_identifier} - #{serial_number}"
  end

 # Constant for provider #
  def self.provider
    Client.active.map { |e| [e.name,e.id] }.unshift(['Clarion',''])
  end

  self.status.keys.each do |s|
    scope s.to_sym, -> { where(status: s) }
  end

  # scope to get unassigned devices
  scope :unassigned, -> { where(status: 'instock') }

  # scope to get parent devices
  scope :parent_devices, ->(*id) { active.where(parent_id: nil).where.not(id: id) }

  # scope to get childern devices
  scope :child_devices, ->(*id) { where(parent_id: id) }

  # Class method for search devices#
  def self.search(search)
    where(%q[ lower(device_identifier) LIKE :keyword OR model_number LIKE :keyword],:keyword=>"%#{search}%".downcase).active
  end

  def current_employee(on_date = Date.today)
    assignment_on_date(on_date).try(:employee) if self.status == 'assigned'
  end

  def assignment_on_date(on_date = Date.today)
    self.device_assignments.where("assign_date <= ?", on_date).order(assign_date: :desc, updated_at: :desc).first
  end

  def to_status
    Device.status[self.status.to_sym]
  end

  def self.test_uniquness(params)
    if params[:id].present?
      Device.where.not(id: params[:id]).where(serial_number: params[:serial_number]).present? ? false : true
    else
      Device.where(serial_number: params[:serial_number]).present? ? false : true
    end
  end

  def add_more_devices(more_device_params)
    more_device_params.values.each do |device_param|
      d = dup
      d.model_number = device_param[:model_number]
      d.serial_number = device_param[:serial_number]
      d.save
    end  if more_device_params
  end

  def assigned?
    self.device_assignments.where(unassign_date: nil).present?
  end

  private

  #Update child devices as per changes in parent device
  def update_child_devices
    if self.parent_id.blank? && !['assigned', 'instock'].include?(self.status)
      params_attr = {status: 'instock', parent_id: nil} 
    else
      params_attr = {status: self.status, parent_id: self.id}
    end
    self.child_devices.update_all(params_attr)
  end

  def check_lifetime_warranty
    if lifetime_warranty == true 
      self.warranry_year = nil  
      self.warranry_month= nil 
    end
  end

  def release_resources
    if deleted_at.present?
      device_assignments.where(unassign_date: nil).update_all(unassign_date: DateTime.now)
    end
  end

  def check_purchase_date
    errors.add(:purchase_date, "Purcharse Date can't be future") if self.purchase_date.present? && self.purchase_date.to_date > Date.today
  end

  #Check status validation as per parent device
  def check_valid_status
    if self.parent_id.present?
      errors.add(:parent_id, 'Assoicated Device is invalid') if self.child_devices.size > 0
      errors.add(:parent_id, 'Assoicated Device should be In-Stock or Assigned') unless ['instock', 'assigned'].include?(self.parent.status)
      errors.add(:status, 'Status should be equal to Assoicated Device') if self.status != self.parent.status
      errors.add(:branch_id, 'Branch should be as per Assoicated Device') if self.branch_id.present? && self.branch_id != self.parent.branch_id
    else
      if self.parent_id_was.present? && self.status == 'assigned'
        errors.add(:parent_id, "Assoicated Device can't be blank")   
        errors.add(:status, "Assigned status can't select without Assoicated Device")
      end
      errors.add(:status, "Assigned status is invalid") if self.status == 'assigned' && !self.assigned?
    end
  end
end

Arpit/asset_management/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy, :destroy_assignment]
  before_action :device_categories, :employees, :branches, only: [:edit, :update, :new, :create]

  # GET /device
  # GET /device.json
  def index
    @devices = Device.send(params[:deleted] ? :inactive : :active)
  end

  # GET /device/1
  # GET /device/1.json
  def show
    @devices = @device.child_devices
  end

  # GET /device/new
  def new
    @device = Device.new
    @device.more_devices.build
  end

  # GET /device/1/edit
  def edit
    @parent_devices = (@device.branch.devices.where(parent_id: nil, status: ['assigned', 'instock']).active << @device.parent).compact.uniq
    redirect_to devices_path, alert: "You can't edit this device." if @device.deleted_at.present?
  end

  # POST /device
  # POST /device.json
  def create
    params[:device].merge!(params[:device][:more_devices_attributes].first[1])  if params[:device][:more_devices_attributes].first
    params[:device][:more_devices_attributes].except!(params[:device][:more_devices_attributes].keys.first) if params[:device][:more_devices_attributes].first   
    @device = Device.new(device_params)
    @device.status_date = Date.today
	  @device.status = @device.parent_id.present? ? @device.parent.status : 'instock'
    if Device.test_uniquness(params)
      respond_to do |format|
        if @device.save
          @device.add_more_devices(params[:device][:more_devices_attributes])
          format.html { redirect_to devices_url, notice: "Device(s) successfully created." }
          format.json { render :show, status: :created, location: @device }
        else
          format.html { render :new }
          format.json { render json: @device.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "Serial Numbers are alredy been taken"
      params[:device][:more_devices_attributes].values.each do |device|
        @device.more_devices.build(serial_number: device['serial_number'],model_number: device['model_number'])
      end if params[:device][:more_devices_attributes]
      @parent_devices = (@device.branch.devices.where(parent_id: nil, status: ['assigned', 'instock']).active << @device.parent).compact.uniq
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device/1
  # PATCH/PUT /device/1.json
  def update
    @device.status_date = Date.today
    respond_to do |format|
      @device.parent_id = device_params[:parent_id]
      device_attr = device_params
      device_attr[:status] = @device.parent.status if device_attr[:status].blank?
      device_attr[:branch_id] = @device.parent.branch_id if device_attr[:branch_id].blank?

      if @device.update(device_attr)
        if @device.status != 'assigned'
          @device.device_assignments.where(unassign_date: nil).update_all(unassign_date: DateTime.now)  
        end
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        @parent_devices = (@device.branch.devices.where(parent_id: nil, status: ['assigned', 'instock']).active << @device.parent).compact.uniq
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device/1
  # DELETE /device/1.json
  def destroy
    @device = Device.find(params[:id])
    if @device.device_category.deleted_at.present?
      message = {alert: 'This device can not be reverted. Device Category is not available'}
    else
      update_params = {status: 'instock', employee_id: nil, deleted_at: (params[:revert] ? nil : DateTime.now)}
      Device.child_devices(@device.id).update_all(update_params)
      @device.update(update_params)
      message = {notice: "Device was successfully #{params[:revert] ? 'reverted' : 'deleted'}."}
    end
    respond_to do |format|
      format.html { redirect_to devices_url, message  }
      format.json { head :no_content }
    end
  end

  def assignment
    if params[:device].present?
      @device = Device.new(branch_id: device_params[:branch_id], device_category_id: device_params[:device_category_id])
      @branch = @device.branch
      @devices = @branch.devices.where(status: 'instock', device_category_id: @device.device_category_id)
      @employees = @branch.employees
      @device_assignment = DeviceAssignment.new(device_params[:device_assignments])
    else
      @device = Device.new()
      @device.device_assignments.build
    end
    respond_to do |format|
      if params[:device].present? && device_params.key?(:device_assignments) && @device_assignment.valid?
        assignment = device_params[:device_assignments]
        DeviceAssignment.create_assignment(assignment[:device_id], assignment[:employee_id], assignment[:assign_date])
        Device.find(assignment[:device_id]).update(status: 'assigned', employee_id: assignment[:employee_id], assign_date: assignment[:assign_date])
        format.html { redirect_to(device_path(id: assignment[:device_id]), notice: 'Device Assignment was successfully created.')}
      else
        format.html { render :assignment }
      end
    end
  end

  def destroy_assignment
    DeviceAssignment.find(params[:device_assignment_id]).try(:destroy)
    @device.update(status: 'instock', employee_id: nil) if @device.device_assignments.where(unassign_date: nil).blank?
    redirect_to(device_path(id: params[:id]), notice: 'Device Assignment was successfully destroyed.')
  end

  def update_assignment
    respond_to do |format|
      @device_assignment = DeviceAssignment.find(params[:device_assignment_id])
      if @device_assignment.update(unassign_date: params[:unassign_date])
        @device_assignment.device.update(status: 'instock', employee_id: nil) if @device_assignment.unassign_date_was.present?
        message = {notice: 'Device Assignment was successfully updated.', unassign_date: @device_assignment.unassign_date.to_s, status: @device_assignment.device.to_status}
      else
        message = {errors: @device_assignment.errors.messages.values.join('</br>')||'Device Assignment cannot be update to this date'}
      end
      format.json { render :json => message }
    end
  end

  def check_serial_uniqueness
    if Device.test_uniquness(params)
      render :text => 0 and return false 
    else
      render :text => 1 and return false 
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:invoice_id, :vendor_id, :serial_number, :model_number, :ip_address, :status, :status_date, :branch_id, :warranty, :client_id, :device_category_id, :parent_id, :employee_id, :deleted_at, :device_identifier, :purchase_date, :lifetime_warranty, :warranry_year, :warranry_month, device_assignments: [:employee_id, :device_id, :assign_date] )
    end

    def device_categories
      @device_categories = DeviceCategory.active
    end

    def employees
      @employees = @device.present? ? @device.branch.employees : Employee.active
    end

    def branches
      @branches = Branch.active
    end
end

Arpit/asset_management/app/helpers/devices_helper.rb
module DevicesHelper
end

Arpit/asset_management/app/views/devices/_devices.html.haml
- id = params[:search].present? ? "search_data_table" : "data_table"
%table{id: id, class: "table table-striped table-bordered"}
  %thead
    %tr
      %th Name
      %th Serial Number
      %th Category
      %th Model Number
      %th Branch
      - if params[:deleted].blank?
        %th Status
      %th Branch
      %th Provider
      = deleted_on_th
      - unless params[:search].present?
        = actions_th
  %tbody
    - @devices.each do |device|
      %tr
        %td= link_to device.device_identifier, device
        %td= device.serial_number
        %td= device.device_category.try(:name)
        %td= device.model_number
        %td= device.branch.try(:name)
        - if params[:deleted].blank?
          %td= device.to_status
        %td= device.branch.try(:name)
        %td= device.client.present? ? device.client.name : 'Clarion'
        = deleted_at(device)
        
        -if params[:deleted].present?
          %td.text-center
            = link_to '', device_url(device,revert: true), :method => :delete, class: "glyphicon glyphicon-repeat edit-link", title: "Revert", :data => { :confirm => "Are you sure you want to revert device: #{device.name}?" }
        -elsif !params[:search].present?
          %td.text-center
            = link_to '', device, class: "glyphicon glyphicon-eye-open show-link", title: "Show"
            = link_to '', edit_device_path(device), class: "glyphicon glyphicon-pencil edit-link", title: "Edit"
            = link_to '', device, :method => :delete, class: "glyphicon glyphicon-remove-circle delete-link", title: "Delete", :data => { :confirm => "Are you sure you want to delete device: #{device.name}?/n" }

Arpit/asset_management/app/views/devices/_form.html.haml
- edit_parent = @device.child_devices.size != 0
- parent_select = (@parent_devices||[]).group_by{|s| s.status}.map{|status, values| [Device.status[status.to_sym], values.map{|s| [s.name, s.id]}]}
.row
  .col-md-5
    = f.select :device_category_id, @device_categories.map{ |a| [a.name, a.id] }, { prompt: 'Select Category', label: "Device Category<span class='required'/>".html_safe }, data: { 'rule-required' => true }
    = f.text_field :device_identifier, data: { 'rule-required' => true, 'rule-maxlength' => 35, 'msg-maxlength' => "Maximum 35 characters", 'title' => "Maximum 35 characters", 'rule-validName' => true }, class: "input_tooltip", label: "Name<span class='required'/>".html_safe, maxlength: 35
    = f.select :parent_id, parent_select, { include_blank: 'Select Associated Device', label: "Associated Device"}, {is_parent: @device.parent_id.blank?}
    = f.select :client_id, Device.provider, label: "Provider"
  .col-md-5
    = f.text_field :purchase_date, placeholder: 'dd/mm/yyyy', label: "Purchase Date <span class='required'/>".html_safe, data: { 'rule-required' => true,  'rule-dateFormat' => true, 'behaviour' => 'no-future-datetimepicker' }  
    = f.collection_select :branch_id, @branches, :id, :name, { include_blank: 'Select Branch', label: "Branch<span class='required'/>".html_safe }, data: { 'rule-required' => true }, class: 'branch_select'
    = f.text_field :ip_address, data: { 'rule-ipv4' => true, 'msg-ipv4' => "Please enter an valid IP Address" }, label: "IP Address"
    - unless @device.new?
      = f.select :status, Device.status.invert, {include_blank: 'Select Status', label: "Status<span class='required'/>".html_safe }, data: {assigned: @device.status!='assigned'}
.row
  .col-md-5
    .form-group
      %label.control-label.col-sm-5{:for => "warranty"} Warranty
      .col-sm-7
        = f.check_box :lifetime_warranty ,checked: @device.lifetime_warranty == true ? true : false
#warrenty_values{style: "#{@device.lifetime_warranty == true ? 'display:none' : ''}"}
  .row
    .col-md-5
      = f.text_field :warranry_year, data: { 'rule-required' => true, 'rule-RealNumber' => true, 'msg-maxlength' => "Maximum 2 digits", title: "Maximum 2 digits" }, label: "Years<span class='required'/>".html_safe, class: "input_tooltip #{@device.lifetime_warranty == true ? 'ignore' : ''}", maxlength: 2
    .col-md-5
      = f.text_field :warranry_month, data: {'rule-month' =>true, 'rule-RealNumber' => true, 'rule-required' => true, 'msg-maxlength' => "Maximum 2 digits", title: "Maximum 2 digits" }, label: "Months<span class='required'/>".html_safe, class: "input_tooltip #{@device.lifetime_warranty == true ? 'ignore' : ''}", maxlength: 2

- if @device.new?
  .row
    .col-md-5
      .form-group
        %label.control-label.col-sm-5{:for => ""} Qantity
        .col-sm-2
          = link_to '<span class="glyphicon glyphicon-minus-sign"></span>'.html_safe,"javascript:void(0)", id: "remove-device" ,:disabled=> "disabled", :data => { :target => "#more_devices" }, class: "btn btn-danger",style:'height:33px'
        .col-sm-3
          %input#size.form-control.input_tooltip.text-center{:name => "size", :size => "3", :title => "", :type => "text",:value=> "1" ,:disabled=> true,'data-rule-validateMaxDevice' => true} 
        .col-sm-2
          = f.link_to_add '<span class="glyphicon glyphicon-plus-sign"></span>'.html_safe, :more_devices, :data => { :target => "#more_devices" }, class: "btn btn-primary nested-add",style:'height:33px'

// In case of new devices we can add multiple records for then same devices ex. mouse . We have to change give only serial number and model number and duplicate record will be created
- if @device.new_record?
  #more_devices
    = f.fields_for :more_devices, :wrapper => false,label_col: "col-sm-5",control_col: "col-sm-7"  do |fields|
      .row.nested_div
        =render 'serial_and_model_fields', f: fields
        .col-md-1.padding-top9.hide
          = fields.link_to_remove "", class: "glyphicon glyphicon-minus-sign delete-link nested-remove"
 
- else
  .row
    =render 'serial_and_model_fields' ,f: f
  = hidden_field_tag :id,@device.id
.gap
= f.button(type: 'submit', class: "btn btn-success") do
  %i{ class: "glyphicon glyphicon-ok" }
  Save

= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, devices_path, class: "btn btn-primary"

Arpit/asset_management/app/views/devices/_serial_and_model_fields.html.haml
.col-md-5
  = f.text_field :serial_number, data: { 'rule-uniqueSerial' =>true, 'rule-required' => true, 'msg-maxlength' => "Maximum 35 characters", title: "Maximum 35 characters" }, label: "Serial Number<span class='required'/>".html_safe, class: "input_tooltip", maxlength: 35
.col-md-5
  = f.text_field :model_number, data: { 'rule-required' => true, 'msg-maxlength' => "Maximum 35 characters", title: "Maximum 35 characters" }, label: "Model Number<span class='required'/>".html_safe, class: "input_tooltip", maxlength: 35

Arpit/asset_management/app/views/devices/assignment.html.haml
%h3 Devices Assignment
= bootstrap_form_for @device, url: assignment_devices_path, layout: :horizontal, control_col: "col-sm-3", html: { class: 'validate-form' }  do |d|
  = d.collection_select 'branch_id', Branch.all, :id, :name, {include_blank: 'Please Select',  label: "Branch<span class='required'/>".html_safe}, data: { 'rule-required' => true }, class: 'branch_select'
  = d.collection_select 'device_category_id', DeviceCategory.all, :id, :name, { label: "Device Category<span class='required'/>".html_safe, include_blank: 'Please Select'}, data: { 'rule-required' => true }, class: 'category_select'
  = d.fields_for :device_assignments, @device_assignment do |f|
    = f.collection_select 'device_id', @devices||[], :id, :name, { prompt: 'Please Select', label: "Device<span class='required'/>".html_safe}, data: { 'rule-required' => true }, class: 'device_select'
    = f.collection_select 'employee_id', @employees||[], :id, :name, {prompt: 'Please Select', label: "Employee<span class='required'/>".html_safe}, data: { 'rule-required' => true }, class: "employee_select"
    = f.text_field 'assign_date', placeholder: 'dd/mm/yyyy', label: "Assign Date<span class='required'/>".html_safe, data: { 'behaviour' => 'datepicker', 'rule-required' => true }
  = d.button(type: 'submit', class: "btn btn-success") do
    %i{ class: "glyphicon glyphicon-ok" }
    Save
  = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, devices_path, class: "btn btn-primary"

Arpit/asset_management/app/views/devices/edit.html.haml
%h3 Editing Device
// This is a bootstraped normal form which will only handle single device editing
= bootstrap_form_for @device, layout: :horizontal, control_col: "col-sm-7",label_col: "col-sm-5", html: { class: 'validate-form' }  do |f|
	= render 'form' ,f: f

Arpit/asset_management/app/views/devices/index.html.haml
%h3= "#{deleted_helper} Devices"
= render 'devices'
%br
- unless params[:deleted]
	= link_to '<span class="glyphicon glyphicon-plus-sign"></span> New'.html_safe, new_device_path, class: 'btn btn-primary'
	= link_to '<span class="glyphicon glyphicon-remove-sign"></span> Deleted'.html_safe, devices_path(deleted: true), class: 'btn btn-danger'
	= link_to '<span class="glyphicon glyphicon-check"></span> Assignment'.html_safe, new_device_assignment_path, class: 'btn btn-primary'
-else
	= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, devices_path, class: 'btn btn-primary'

Arpit/asset_management/app/views/devices/new.html.haml
%h3 New Device
// This will generate nested attribute vice bootstraped form 
// Nested form is used for adding multiple assets in single code.
// For editing device it will be only bootstrap_form_for
= bootstrap_nested_form_for @device, layout: :horizontal, control_col: "col-sm-7",label_col: "col-sm-5", html: { class: 'validate-form' }  do |f|
	= render 'form' ,f: f

Arpit/asset_management/app/views/devices/show.html.haml
%h3 Device Details

%table.width-100
  %tr
    %th
      Device Category:
    %td
      = @device.device_category.try(:name)
    %th
      Purchased Date:
    %td
      = @device.purchase_date.try(:to_s, "%b %d, %Y")
  %tr
    %th
      Name:
    %td
      = @device.device_identifier
    %th
      Branch:
    %td
      = @device.branch.try(:name)
  %tr
    - if @devices.blank? && @device.parent_id.present?
      %th
        Associated Device:
      %td
        = link_to format_value(@device.parent.try(:name)), @device.parent
    %th
      IP Address:
    %td
      = format_value(@device.ip_address)
  %tr
    %th
      Provider:
    %td
      = format_value (@device.client.present? ? @device.client.name : 'Clarion')
    %th
      Current Employee:
    %td
      = format_value(@device.current_employee.try(:name))
  %tr
    %th
      Warranty:
    %td
      = @device.lifetime_warranty ? 'Lifetime' : @device.warranry_year.to_i > 0 ? "#{@device.try(:warranry_year)}.#{@device.try(:warranry_month)} Year(s)" : "#{@device.try(:warranry_month)} Month(s)"
    %th
      Status:
    %td.device_status
      = @device.active? ? @device.to_status : 'Deleted'
  %tr
    %th
      Serial Number:
    %td
      = @device.serial_number
    %th
      Model Number:
    %td
      = @device.model_number
  %tr
    %th
      Last Updated:
    %td
      = @device.updated_at.try(:to_s, "%b %d, %Y")

%h3  Employees
%table#search_data_table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Email
      %th Employee Id
      %th.span6 Joined Date
      %th.span6 Assigned Date
      %th.span6 Unassigned On
      - if @device.active?
        = actions_th
  %tbody
    - @device.device_assignments.each do |assignment|
      - employee = assignment.employee
      %tr
        %td= link_to employee.name, employee
        %td= employee.email
        %td= employee.employee_number
        %td.span-6
          = employee.join_date.try(:to_s, "%b %d, %Y")
        %td
          = assignment.assign_date.try(:to_s, "%b %d, %Y")
        %td
          - if assignment.unassign_date.blank?
            - delete_message = 'After deleting this record device will be In Stock'
          - else
            - delete_message = 'Are you sure you want to delete this record?'
          = format_value assignment.unassign_date.try(:to_s, "%b %d, %Y %I:%M %p")
        - if @device.active?
          %td
            = link_to '', edit_device_assignment_path(assignment), class: "glyphicon glyphicon-pencil edit-link", title: "Edit"
            = link_to '', assignment, :method => :delete, class: "glyphicon glyphicon-remove-circle delete-link", title: "Delete", :data => { :confirm => delete_message }
- if @device.parent_id.blank? && @devices.present?
  %h3 Associated Devices
  = render 'devices'

%br
= link_to '<span class="glyphicon glyphicon-pencil "></span> Edit'.html_safe, edit_device_path(@device), class: "btn btn-success" if @device.active?
= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, devices_path, class: "btn btn-primary"