Arpit/asset_management/config/routes.rb
Rails.application.routes.draw do

  resources :invoices do
    collection do
      get 'get_purchase_order'
    end
  end
  get 'download'=> "welcome#download_file",as: :download

  resources :purchase_orders

  resources :transfers do
    member do
      get 'resources'
    end
  end

  resources :quotations do
    member do
      get 'request_vendors'
      get 'get_requests'
    end
  end

  resources :device_requests
  resources :device_assignments
  resources :device_categories

  resources :devices do
    collection do
      get 'assignment'
      post 'check_serial_uniqueness'
      post 'assignment'
      put 'update_assignment'
    end
    member do
      delete 'destroy_assignment'
    end
  end

  namespace :admin do
    resources :users
  end
  resources :clients
  resources :branches do
    member do
      get 'get_employees'
	  get 'associate_data'
    end
  end
  resources :vendors
  resources :software_products
  resources :employees
  get 'welcome/index'  # The priority is based upon order of creation: first created -> highest priority.

  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Arpit/asset_management/app/views/layouts/_footer.html.haml
.navbar.navbar-bottom
  .panel-footer.center.pager
    Assets Management

Arpit/asset_management/app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.top-header{role: "navigation"}
  = link_to "Assets Management", root_path, class: "navbar-brand"
  / - if current_user.present?
  /   = form_tag(root_path, method: :get, class: 'navbar-form navbar-left', role: 'search') do
  /     = text_field_tag :search, params[:search], placeholder: "Search", class: "form-control"
  /     = submit_tag "Submit", :name => nil, class: "btn btn-default"
  %p.navbar-text.navbar-right
    .nav.navbar-nav.navbar-right
      = render 'layouts/header_bar'
- if current_user.present?
  %nav.navbar.navbar-default.top-header{role: "navigation"}
    .container-fluid
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown{class: active_menu('devices')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Assets
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Devices", devices_path,class: active_sub_menu('devices')
              %li
                = link_to "Device Categories", device_categories_path,class: active_sub_menu('device_categories')
              %li
                = link_to "Softwares", software_products_path,class: active_sub_menu('software_products')
          %li.dropdown{class: active_menu('partners')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Partners
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Employees", employees_path,class: active_sub_menu('employees')
              %li
                = link_to "Users", admin_users_path,class: active_sub_menu('users')
              %li
                = link_to "Vendors", vendors_path,class: active_sub_menu('vendors')
              %li
                = link_to "Clients", clients_path,class: active_sub_menu('clients')
          %li.dropdown{class: active_menu('transfers')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Transfers
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Devices", transfers_path(resource: "Device"), class: active_sub_menu('transfers','Device')
              %li
                = link_to "Employees",  transfers_path(resource: "Employee"),class: active_sub_menu('transfers','Employee')
          %li.dropdown{class: active_menu('device_requests')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Transactions
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Requests", device_requests_path, class: active_sub_menu('device_requests')
              %li
                = link_to "Quotations", quotations_path,class: active_sub_menu('quotations')
              %li
                = link_to "Purchase Orders", purchase_orders_path, class: active_sub_menu('purchase_orders')
              %li
                = link_to "Invoices", invoices_path, class: active_sub_menu('invoices')
          %li.dropdown{class: active_menu('locations')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Locations
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Branches", branches_path,class: active_sub_menu('branches')
          %li.dropdown{class: active_menu('reports')}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Reports
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Users", "#",class: active_sub_menu('reports',nil,'users')
              %li
                = link_to "Employees", "#",class: active_sub_menu('reports',nil,'users')
              %li
                = link_to "Devices", "#",class: active_sub_menu('reports',nil,'users')
              %li
                = link_to "Transactions", "#",class: active_sub_menu('reports',nil,'users')

Arpit/asset_management/app/views/layouts/_header_bar.html.haml
%p.navbar-text.pull-right
  - if user_signed_in?
    = link_to current_user.email, edit_admin_user_path(current_user), :class => 'navbar-link'
    |
    = link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'
  - else
    = link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'
    |
    = link_to "Sign In", new_user_session_path, :class => 'navbar-link'

Arpit/asset_management/app/views/layouts/application.html.haml
%html
  %head
    %title= t "page_title.#{controller_name}.#{action_name}"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render 'layouts/header'

    - if notice
      %p.alert.alert-success
        %span.close-icon.glyphicon.glyphicon-remove-circle
        = notice
    - if alert
      %p.alert.alert-danger
        %span.close-icon.glyphicon.glyphicon-remove-circle
        = alert

    .container
      = yield

    = render 'layouts/footer'