Arpit/asset_management/config/routes.rb
Rails.application.routes.draw do

  resources :invoices do
    collection do
      get 'get_purchase_order'
    end
  end
  get 'download'=> "welcome#download_file",as: :download

  resources :purchase_orders

  resources :transfers do
    member do
      get 'resources'
    end
  end

  resources :quotations do
    member do
      get 'request_vendors'
      get 'get_requests'
    end
  end

  resources :device_requests
  resources :device_assignments
  resources :device_categories

  resources :devices do
    collection do
      get 'assignment'
      post 'check_serial_uniqueness'
      post 'assignment'
      put 'update_assignment'
    end
    member do
      delete 'destroy_assignment'
    end
  end

  namespace :admin do
    resources :users
  end
  resources :clients
  resources :branches do
    member do
      get 'get_employees'
	  get 'associate_data'
    end
  end
  resources :vendors
  resources :software_products
  resources :employees
  get 'welcome/index'  # The priority is based upon order of creation: first created -> highest priority.

  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

Arpit/asset_management/app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base

  # Associations
  belongs_to :quotation
  has_many :device_transactions
  has_one :invoice
  has_many :vendors, through: :device_transactions
  has_many :uploads, as: :attachable
  accepts_nested_attributes_for :device_transactions, :allow_destroy => true
  accepts_nested_attributes_for :invoice, :allow_destroy => true
  accepts_nested_attributes_for :uploads, :allow_destroy => true
  attr_accessor :vendor_id

  # Transactions nested attributes
  accepts_nested_attributes_for :device_transactions, :allow_destroy => true

  # Validations
  validates :on_date, :quotation_id, presence: true
  validate :validate_on_date

  # Callback
  before_create :generate_identifier
  after_destroy :nullify_transactions

  # To create transactions after purchase order creation
  def create_transactions(transactions)
    transactions.values.each do |val|
      device_transaction = DeviceTransaction.find(val[:id])
      device_transaction.update(val.merge(purchase_order_id:self.id))
    end
  end

  # To set purchase order attributes
  def set_purchase_order(device_transactions)
    device_transactions.each do |t|
      t.purchase_title = t.quotation_title
      t.purchase_description = t.quotation_description
      t.purchase_price = t.quotation_price
      t.purchase_quantity = t.quotation_quantity
    end
  end

  # To null transactions after purchase order destroy
  def nullify_transactions
    t = DeviceTransaction.where(purchase_order: self.id)
    t.update_all(purchase_order_id: nil, purchase_title: nil, purchase_description: nil, purchase_quantity: nil, purchase_price: nil, purchase_notes: nil)
  end

  def edit?
    self.invoice.blank?
  end

  private

  # To generate unique identifier everytime considering last identifier
  def generate_identifier
    if PurchaseOrder.exists?
      identifier = PurchaseOrder.last.identifier
      identifier = (identifier.gsub("PO", "").to_i + 1).to_s.prepend("PO")
    else
      identifier = "PO1"
    end
    self.identifier = identifier
  end

  # To validate purchase order date that should be after quotation date and before today's date
  def validate_on_date
    quotation = Quotation.find(self.quotation_id)
    current_date = Date.today
    if self.on_date.present?
      self.errors.add :on_date, "Purchase order date can't be future" if self.on_date > current_date
      self.errors.add :on_date, "Purchase order date should be onwards #{quotation.on_date}" if self.on_date < quotation.on_date
    end
  end
end

Arpit/asset_management/app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]
  before_action :set_quotations, only: [:new,:create]
  before_action :check_permission, only: [:edit, :destroy, :update]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    if params[:quotation_id].present?
      @quotation = Quotation.find(params[:quotation_id])
      @device_transactions = @quotation.device_transactions
      @device_transactions.each do |po|
        po.purchase_title = po.quotation_title 
        po.purchase_quantity = po.quotation_quantity
        po.purchase_price = po.quotation_price
        po.purchase_description = po.quotation_description
      end
      #@purchase_order.set_purchase_order(@device_transactions)
    else
      @quotation = Quotation.new
    end
    @purchase_order = @quotation.build_purchase_order
    @uploads =   @purchase_order.uploads.build
    @purchase_order.on_date = @quotation.blank? ? '' : @quotation.on_date
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  # GET /purchase_orders/1/edit
  def edit
    @uploads = @purchase_order.uploads.blank? ? @purchase_order.uploads.build : @purchase_order.uploads  
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    # render text: params.inspect and return false
    @quotation = Quotation.find(params[:quotation_id])
    respond_to do |format|
      if @quotation.update(quotation_params)
        @quotation.device_transactions.update_all(purchase_order_id: @quotation.purchase_order.id)
        # @purchase_order.create_transactions(params[:purchase_order][:device_transactions_attributes])
        format.html { redirect_to @quotation.purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render :show, status: :created, location: @quotation.purchase_order }
      else
        @purchase_order = @quotation.purchase_order
        @device_transactions = @quotation.device_transactions
        @uploads = @purchase_order.uploads.build
        format.html { render :new }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        @quotation.device_transactions.update_all(purchase_order_id: @quotation.purchase_order.id)
        format.html { redirect_to @quotation.purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation.purchase_order }
      else
        @purchase_order = @quotation.purchase_order
        @device_transactions = @quotation.device_transactions
        @uploads = @purchase_order.uploads.blank? ? @purchase_order.uploads.build : @purchase_order.uploads  
        format.html { render :edit }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: 'Purchase order was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.includes(:device_transactions).find(params[:id])
      @device_transactions = @purchase_order.device_transactions
      @quotation = @purchase_order.quotation
    end

    def quotation_params
      params.require(:quotation).permit(:identifier, :quotation_id, :on_date,purchase_order_attributes: [:quotation_id, :on_date,:id,uploads_attributes: [:name,:attachment, :attachment_file_name, :attachment_content_type, :attachment_file_size]],device_transactions_attributes: [:purchase_title, :purchase_quantity, :purchase_price, :purchase_description,:id, :purchase_notes])
    end

    # To display quotations only whose purchase orders are not generated
    def set_quotations
      qid = PurchaseOrder.select(:quotation_id).map(&:quotation_id)
      @quotations = Quotation.where.not(id: qid)
    end

    def check_permission
      redirect_to purchase_orders_path, alert: "You can't edit this Purchase Order." unless @purchase_order.edit?
    end
end

Arpit/asset_management/app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

Arpit/asset_management/app/views/purchase_orders/_form.html.haml
- if @purchase_order.new?
  - url = purchase_orders_path(quotation_id: @quotation.id)
  - method = "post"
-else
  - url = purchase_order_path(@purchase_order, quotation_id: @quotation.id)
  - method = "put"
#purchase_div
  = bootstrap_nested_form_for @quotation, url: url, method: method, layout: :horizontal, control_col: "col-sm-7",label_col: "col-sm-4", html: { class: 'validate-form' }  do |f|
    = f.fields_for :purchase_order, @purchase_order, :wrapper => false do |purchanse_order_field|
      .row
        .col-md-5
          - on_date = ""
          - if @purchase_order.new?
            = purchanse_order_field.collection_select :quotation_id, @quotations||[], :id, :identifier, {include_blank: "Please Select", label: "Quotation <span class='required'/>".html_safe, selected: params[:quotation_id]}, data: {'rule-required' => true}
          - else
            - on_date = @purchase_order.quotation.on_date.to_s
            .form-group
              %label.control-label.col-sm-4{:for => ""} Quotation
              .col-sm-7
                = @purchase_order.quotation.try(:identifier)
      #date-upload-div{class: "#{@quotation.new? ? 'hide row' : 'row' }"}
        .col-md-5
          = purchanse_order_field.text_field :on_date, placeholder: 'dd/mm/yyyy', data: {'start-date' => on_date, 'date-format' =>"DD/MM/YYYY", 'behaviour' => 'no-future-datetimepicker', 'rule-dateFormat' => true, 'rule-required' => true, 'start-date' => @quotation.on_date.to_s }, label: "Date <span class='required'/>".html_safe
        .col-md-5
          = purchanse_order_field.fields_for :uploads,@uploads, :wrapper => false do |attachment_form|
            = attachment_form.file_field :attachment ,accept: ".pdf"
          .text-right
            = link_to "#{@purchase_order.uploads.try(:first).try(:attachment_file_name)}", download_path(id: @purchase_order.uploads.try(:first).try(:id))        
    #device_transactions{style: "#{@quotation.new? ? 'display:none' : '' }"}
      = render "/shared/device_transactions", type: "purchase_",f: f

    .row
      #loading_div.col-md-2.col-md-offset-5.hide
        %content
          %section
            .loadingspin

    .row
      = f.button(type: 'submit', class: "btn btn-success") do
        %i{ class: "glyphicon glyphicon-ok" }
        Save
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, purchase_orders_path, class: "btn btn-primary"

Arpit/asset_management/app/views/purchase_orders/edit.html.haml
%h3 Editing Purchase Order

= render 'form'

Arpit/asset_management/app/views/purchase_orders/index.html.haml
%h3= "#{deleted_helper} Purchase Orders"

%table#data_table.table.table-striped.table-bordered
  %thead
    %tr
      %th Identifier
      %th Quotation
      %th Title
      %th Device Category
      %th Vendor
      %th Date
      = deleted_on_th
      = actions_th
  %tbody
    - @purchase_orders.each do |purchase_order|
      - transactions = purchase_order.device_transactions
      - categories = transactions.map(&:device_category)
      - vendors = transactions.map(&:vendor)
      %tr
        %td= link_to purchase_order.identifier, purchase_order
        %td= link_to purchase_order.quotation.identifier, purchase_order.quotation
        %td= purchase_order.device_transactions.map(&:purchase_title).uniq.join(', ')
        %td= categories.compact.map(&:name).uniq.join(', ') if categories.present?
        %td= vendors.compact.map(&:name).uniq.join(', ') if vendors.present?
        %td= purchase_order.on_date.to_s("%b %d, %Y")
        = deleted_at(purchase_order)
        %td.text-center
          = link_to '', purchase_order, class: "glyphicon glyphicon-eye-open show-link", title: "Show"
          - if purchase_order.edit?
            = link_to '', edit_purchase_order_path(purchase_order), class: "glyphicon glyphicon-pencil edit-link", title: "Edit"
            = link_to '', purchase_order, :method => :delete, class: "glyphicon glyphicon-remove-circle delete-link", title: "Delete",  :data => { :confirm => "Are you sure you want to delete Purchase Order: #{purchase_order.identifier}?" }
%br
= link_to '<span class="glyphicon glyphicon-plus-sign"></span> New'.html_safe, new_purchase_order_path, class: 'btn btn-primary'

Arpit/asset_management/app/views/purchase_orders/new.html.haml
%h3 New Purchase Order

= render 'form'

Arpit/asset_management/app/views/purchase_orders/show.html.haml
%h3 Purchase Order Detail

%table.width-100
  %tr
    %th Identifier:
    %td= @purchase_order.identifier
  %tr
    %th Date:
    %td= @purchase_order.on_date.try(:to_s, "%b %d, %Y")
  %tr
    %th Quotation:
    %td= @purchase_order.quotation.try(&:identifier)
  %tr
    %th Vendor:
    %td= @purchase_order.vendors.uniq.map(&:name).join(', ')
  %tr
    %th Attchment:
    %td= link_to "#{@purchase_order.uploads.try(:first).try(:attachment_file_name)}", download_path(id: @purchase_order.uploads.try(:first).try(:id))

%br
%table.table.table-striped.table-bordered
  %thead
    %th Device Category
    %th Title
    %th Description
    %th Quantity
    %th 
      Price
      %small (per unit)
    %th Total
  %tbody
    - total = 0
    - @purchase_order.device_transactions.each do |t|
      %tr
        %td= t.device_category.try(:name)
        %td= t.purchase_title
        %td= t.purchase_description
        %td= t.purchase_quantity
        %td= t.purchase_price
        %td.text-right
          %b
            = t.purchase_subtotal
            - total += t.purchase_subtotal
  %tr
    %td
      %b Total
    %td.text-right{colspan: 5}
      %b
        = total
%br
- if @purchase_order.edit?
  = link_to '<span class="glyphicon glyphicon-pencil "></span> Edit'.html_safe, edit_purchase_order_path(@purchase_order), class: "btn btn-success" if @purchase_order.active?
= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, purchase_orders_path, class: "btn btn-primary"